Add CI steps to test new push-workflow
Test that if a non-fast-forwardable merging situation arises and
`--force` is not added, the action will fail.

Also, make sure the target branch that's checked out actually has the
remote set as the upstream branch.

Minor word changes in user messages.

Make new steps a separate CI job.

Note: Status checks must finish even when force pushing.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -119,9 +119,52 @@ jobs:
       with:
         token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
         branch: protected
+        unprotect_reviews: true
+
+  force-pushing:
+    needs: [protected]
+    runs-on: ubuntu-latest
+    name: Testing - protected (--force)
+    steps:
+    - name: Use local action (checkout)
+      uses: actions/checkout@v2
+
+    - name: Perform non-fast-forwardable changes
+      run: |
+        git config --global user.email "casper+github@welzel.nu"
+        git config --global user.name "Casper Welzel Andersen"
+
+        git fetch origin
+        git reset --hard ${{ github.sha }}
+        touch test.txt
+        git add test.txt
+        git commit -m "Diverged from remote branch"
+
+    - name: Push not using `--force` (should fail)
+      id: push_no_force
+      continue-on-error: true
+      uses: ./
+      with:
+        token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
+        branch: protected
+        unprotect_reviews: true
+
+    - name: This runs ONLY if the previous step doesn't fail
+      if: steps.push_no_force.outcome != 'failure' || steps.push_no_force.conclusion != 'success'
+      run: |
+        echo "Outcome: ${{ steps.push_no_force.outcome }} (not 'failure'), Conclusion: ${{ steps.push_no_force.conclusion }} (not 'success')"
+        exit 1
+
+    - name: Push using `--force` (should succeed)
+      uses: ./
+      with:
+        token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
+        branch: protected
+        unprotect_reviews: true
+        force: yes
 
   reset_test_branches_v1:
-    needs: [not_protected, protected]
+    needs: [not_protected, protected, force-pushing]
     runs-on: ubuntu-latest
     name: Reset test branches - v1
     steps:
@@ -229,3 +272,45 @@ jobs:
       with:
         token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
         branch: protected
+
+  force-pushing_v1:
+    needs: [protected_v1]
+    runs-on: ubuntu-latest
+    name: Testing - protected (--force) - v1
+    steps:
+    - name: Use local action (checkout)
+      uses: actions/checkout@v1
+
+    - name: Perform non-fast-forwardable changes
+      run: |
+        git config --global user.email "casper+github@welzel.nu"
+        git config --global user.name "Casper Welzel Andersen"
+
+        git fetch origin
+        git reset --hard ${{ github.sha }}
+        touch test.txt
+        git add test.txt
+        git commit -m "Diverged from remote branch"
+
+    - name: Push not using `--force` (should fail)
+      id: push_no_force
+      continue-on-error: true
+      uses: ./
+      with:
+        token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
+        branch: protected
+        unprotect_reviews: true
+
+    - name: This runs ONLY if the previous step doesn't fail
+      if: steps.push_no_force.outcome != 'failure' || steps.push_no_force.conclusion != 'success'
+      run: |
+        echo "Outcome: ${{ steps.push_no_force.outcome }} (not 'failure'), Conclusion: ${{ steps.push_no_force.conclusion }} (not 'success')"
+        exit 1
+
+    - name: Push using `--force` (should succeed)
+      uses: ./
+      with:
+        token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
+        branch: protected
+        unprotect_reviews: true
+        force: yes
