Add custom acceptable job run conclusions (#204)
Add `acceptable_conclusions` as an action input parameter.
It is a comma-separated list of acceptable conclusions for _all_ status
checks.

Use acceptable_conclusions in CI.
Add skipped mock status check job to test `acceptable_conclusions`.

The parsed acceptable conclusions are validated as a list of unique,
valid conclusions according to GitHub Docs.

Rewrite how checks are waited for.
Use trap to do cleanup in `entrypoint.sh`.

---

Add fail_fast input.
It is a boolean input to determine whether or not to immediately fail
if a status check fails or wait for all checks to finish before failing.

Add fail_fast CI job.
Add another skipped mock status check job to test `fail_fast`.

**IMPORTANT**:
To ensure fail_fast actually works as intended, one needs to manually
check the output in the CI job to see if it truly works and doesn't
ignore the option.

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -103,6 +103,7 @@ jobs:
         token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
         branch: protected
         unprotect_reviews: true
+        acceptable_conclusions: success,skipped
 
     - name: Pushing to a protected branch without any changes
       uses: ./
@@ -110,6 +111,7 @@ jobs:
         token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
         ref: refs/heads/protected
         unprotect_reviews: true
+        acceptable_conclusions: success,skipped
 
   force-pushing:
     needs: [protected]
@@ -138,6 +140,7 @@ jobs:
         token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
         branch: protected
         unprotect_reviews: true
+        acceptable_conclusions: success,skipped
 
     - name: This runs ONLY if the previous step doesn't fail
       if: steps.push_no_force.outcome != 'failure' || steps.push_no_force.conclusion != 'success'
@@ -152,6 +155,7 @@ jobs:
         branch: protected
         unprotect_reviews: true
         force: yes
+        acceptable_conclusions: success,skipped
 
   branch_and_ref:
     needs: [force-pushing]
@@ -218,7 +222,66 @@ jobs:
         unprotect_reviews: true
         path: sub_folder
         force: yes
-        debug: true
+        acceptable_conclusions: success,skipped
+
+  acceptable_conclusions:
+    needs: [path]
+    runs-on: ubuntu-latest
+    name: Testing - Default for `acceptable_conclusions` with skipped checks
+    steps:
+      - name: Use local action (checkout)
+        uses: actions/checkout@v4
+
+      - name: Perform changes
+        run: ./ci.sh
+        working-directory: .github/utils
+
+      - name: Push to protected branch without 'skipped' in 'acceptable_conclusions'
+        id: push_skipped
+        continue-on-error: true
+        uses: ./
+        with:
+          token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
+          branch: protected
+          unprotect_reviews: true
+          # Default value - set here explicitly for clarity
+          acceptable_conclusions: success
+
+      - name: This runs ONLY if the previous step doesn't fail
+        if: steps.push_skipped.outcome != 'failure' || steps.push_skipped.conclusion != 'success'
+        run: |
+          echo "Outcome: ${{ steps.push_skipped.outcome }} (not 'failure'), Conclusion: ${{ steps.push_skipped.conclusion }} (not 'success')"
+          exit 1
+
+  fail_fast:
+    needs: [acceptable_conclusions]
+    runs-on: ubuntu-latest
+    name: Testing - Using `fail_fast`
+    steps:
+      - name: Use local action (checkout)
+        uses: actions/checkout@v4
+
+      - name: Perform changes
+        run: ./ci.sh
+        working-directory: .github/utils
+
+      - name: Push to protected branch without 'skipped' in 'acceptable_conclusions' & with 'fail_fast'
+        id: fail_fast
+        continue-on-error: true
+        uses: ./
+        with:
+          token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
+          branch: protected
+          unprotect_reviews: true
+          # Default value - set here explicitly for clarity
+          acceptable_conclusions: success
+          fail_fast: true
+
+      - name: This runs ONLY if the previous step doesn't fail
+        if: steps.fail_fast.outcome != 'failure' || steps.fail_fast.conclusion != 'success'
+        run: |
+          echo "Outcome: ${{ steps.fail_fast.outcome }} (not 'failure'), Conclusion: ${{ steps.fail_fast.conclusion }} (not 'success')"
+          exit 1
 
   pre-commit:
     runs-on: ubuntu-latest
