Check branch validity - extra fallback to `master`

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -160,7 +160,7 @@ jobs:
   branch_and_ref:
     needs: [force-pushing]
     runs-on: ubuntu-latest
-    name: Test setting `branch` and `ref` fails
+    name: Testing - Setting `branch` and `ref` fails
     steps:
     - name: Use local action (checkout)
       uses: actions/checkout@v2
@@ -181,8 +181,31 @@ jobs:
         echo "Outcome: ${{ steps.push_branch_ref.outcome }} (not 'failure'), Conclusion: ${{ steps.push_branch_ref.conclusion }} (not 'success')"
         exit 1
 
+  non_existant_branch:
+    needs: [branch_and_ref]
+    runs-on: ubuntu-latest
+    name: Testing - Fail for non-existant branch
+    steps:
+    - name: Use local action (checkout)
+      uses: actions/checkout@v2
+
+    - name: Push to non-existant branch (should fail)
+      id: push_non_existant
+      continue-on-error: true
+      uses: ./
+      with:
+        token: '${{ secrets.GITHUB_TOKEN }}'
+        branch: non-existant-branch
+        unprotect_reviews: false
+
+    - name: This runs ONLY if the previous step doesn't fail
+      if: steps.push_non_existant.outcome != 'failure' || steps.push_non_existant.conclusion != 'success'
+      run: |
+        echo "Outcome: ${{ steps.push_non_existant.outcome }} (not 'failure'), Conclusion: ${{ steps.push_non_existant.conclusion }} (not 'success')"
+        exit 1
+
   reset_test_branches_v1:
-    needs: [not_protected, protected, force-pushing, branch_and_ref]
+    needs: [not_protected, protected, force-pushing, branch_and_ref, non_existant_branch]
     runs-on: ubuntu-latest
     name: Reset test branches - v1
     steps:
@@ -333,7 +356,7 @@ jobs:
   branch_and_ref_v1:
     needs: [force-pushing_v1]
     runs-on: ubuntu-latest
-    name: Test setting `branch` and `ref` fails - v1
+    name: Testing - Setting `branch` and `ref` fails - v1
     steps:
     - name: Use local action (checkout)
       uses: actions/checkout@v1
@@ -352,6 +375,29 @@ jobs:
       if: steps.push_branch_ref.outcome != 'failure' || steps.push_branch_ref.conclusion != 'success'
       run: |
         echo "Outcome: ${{ steps.push_branch_ref.outcome }} (not 'failure'), Conclusion: ${{ steps.push_branch_ref.conclusion }} (not 'success')"
+        exit 1
+
+  non_existant_branch_v1:
+    needs: [branch_and_ref_v1]
+    runs-on: ubuntu-latest
+    name: Testing - Fail for non-existant branch - v1
+    steps:
+    - name: Use local action (checkout)
+      uses: actions/checkout@v1
+
+    - name: Push to non-existant branch (should fail)
+      id: push_non_existant
+      continue-on-error: true
+      uses: ./
+      with:
+        token: '${{ secrets.GITHUB_TOKEN }}'
+        branch: non-existant-branch
+        unprotect_reviews: false
+
+    - name: This runs ONLY if the previous step doesn't fail
+      if: steps.push_non_existant.outcome != 'failure' || steps.push_non_existant.conclusion != 'success'
+      run: |
+        echo "Outcome: ${{ steps.push_non_existant.outcome }} (not 'failure'), Conclusion: ${{ steps.push_non_existant.conclusion }} (not 'success')"
         exit 1
 
   pre-commit:
